# Generated by Django 5.2.7 on 2025-11-18 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('funcao', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('presidente', models.BooleanField(default=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ano_atuacao', models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='Ano de atuação')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventariante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.IntegerField(unique=True, verbose_name='Patrimônio')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conta_contabil', models.CharField(blank=True, max_length=50, null=True)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('empenho', models.CharField(blank=True, max_length=50, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('data_documento', models.DateField(blank=True, null=True)),
                ('data_ateste', models.DateField(blank=True, null=True)),
                ('dependencia', models.CharField(blank=True, max_length=100, null=True)),
                ('situacao', models.CharField(choices=[('localizado', 'Localizado'), ('nao_localizado', 'Não Localizado'), ('calamidade', 'Perda por Calamidade')], default='localizado', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_inventario', models.DateField(blank=True, null=True)),
                ('inventariante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonios', to='app.inventariante')),
            ],
        ),
    ]
