# Generated by Django 5.2.7 on 2025-11-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariante',
            name='email',
        ),
        migrations.AlterField(
            model_name='inventariante',
            name='ano_atuacao',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Ano de atuação'),
        ),
        migrations.AlterField(
            model_name='inventariante',
            name='presidente',
            field=models.BooleanField(default=False),
        ),
    ]
