# Generated by Django 5.2.7 on 2025-12-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_registroplanilha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrimonio',
            name='patrimonio',
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='tombo',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='tombo'),
        ),
    ]
